name: Print Hello World

on:
  push:
    branches:
      - main  # Triggers the workflow on push to the 'main' branch

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello World
        run: echo "Hello, World!"
